[project]
name = "my-python-app"
version = "0.1.0"
description = "Add your description here"
readme = "../README.md"
requires-python = ">=3.10"
dependencies = [
    "maturin>=1.8.3",
    "celery[redis]>=5.3.0",
]
